name: build site

description: build site artifacts

runs:
  using: 'composite'
  steps:
    - name: restore build artifacts
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: true
        path: |
          packages/*/dist
        key: ${{ runner.os }}-build-artifacts-${{ hashfiles('packages/*/src', 'packages/*/package.json', '!packages/casts-theme/src/tokens/ts') }}

    - name: build site
      # run: pnpm --filter 'site' build && cp ./site/dist/index.html ./site/dist/404.html
      run: pnpm --filter 'site' build:ssg
      shell: bash
