// @ts-ignore example should import React
import React from 'react';
import { Col, Row } from '@casts/grid';
import { Space } from '@casts/space';

import './styles.scss';

export const GridResponsiveDemo = () => {
  return (
    <Space className="demo-grid" direction="vertical">
      <Row gutter={[8, 8]}>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
        <Col
          span={24}
          xsmall={24}
          small={12}
          medium={8}
          large={6}
          xlarge={3}
          xxlarge={2}
        >
          <div>col</div>
        </Col>
      </Row>
    </Space>
  );
};

export default GridResponsiveDemo;
